### ISSUE TITLE
Wakeup Period appears backwards next to other jumpers

### ISSUE THREAD

**Issue by crouchingbadger** [OxFloodNet/sensor-device#11]
Jumpers for Node ID read from left to right MSB-LSB, but Wakeup Period bit values are LSB-MSB.

We should swap them around so D10 is Most Significant Bit and D9 is Least Significant so it reads correctly alongside the Node ID.

**Comment by thiseldo** [comment]
This has changed in V4 firmware, pins are labeled 1 and 2, but still map to D9 and D10.

**Comment by crouchingbadger** [comment]
As there is now only one direction to read (ID headers have gone in v4.1) I will close this.
