### ISSUE TITLE
re: Wirelessthings 

### ISSUE THREAD

**Issue by ghost** [OxFloodNet/sensor-device#15]
Hi, 

1000 apologies, not really an issue, but I couldn't see any private email addreses. 

I am aware you use  WirelessThings/Ciseco radios, like myself and it would appear they are closing. 

OpenMicros site & WirelessThings site are down, although the latter was up not so long ago.

Ref:
http://www.insidermedia.com/insider/midlands/365agile-confirms-nottingham-closure

Rgds,
Chris.

**Comment by crouchingbadger** [comment]
Thanks for letting us know. This has been circulating for a while. 

We've moved to using LoRaWAN modules from Multitech which are a good near compatible replacement for hardware, but the code is now in mbed. 2nd Generation devices are based on this combination instead. They're Things Network compatible which will help with coverage.

As for getting parts for 1st generation devices I guess this is your last chance if you want to build them :-/
